import * as esbuild from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");

const outFile = resolve(__dirname, "dist/widget.js");
const workerBundle = resolve(__dirname, "../worker/src/generated/widgetBundle.ts");

/** Emit the built JS into the worker as an exported string so the worker can serve it. */
function syncToWorker() {
  const js = readFileSync(outFile, "utf8");
  const escaped = JSON.stringify(js);
  mkdirSync(dirname(workerBundle), { recursive: true });
  writeFileSync(
    workerBundle,
    `// Auto-generated by widget/build.mjs. Do not edit by hand.\nexport const WIDGET_JS = ${escaped};\n`,
  );
  console.log(`[widget] built ${(js.length / 1024).toFixed(1)} KB -> dist/widget.js + worker bundle`);
}

const options = {
  entryPoints: [resolve(__dirname, "src/index.ts")],
  outfile: outFile,
  bundle: true,
  format: "iife",
  target: ["es2020"],
  minify: !watch,
  sourcemap: false,
  legalComments: "none",
};

if (watch) {
  const ctx = await esbuild.context({
    ...options,
    plugins: [
      {
        name: "sync-to-worker",
        setup(build) {
          build.onEnd((result) => {
            if (result.errors.length === 0) syncToWorker();
          });
        },
      },
    ],
  });
  await ctx.watch();
  console.log("[widget] watching for changes…");
} else {
  await esbuild.build(options);
  syncToWorker();
}
